# --------------------------------------------------------------------------------------------------
# SPDX-FileCopyrightText: 2026 BESA developers
# SPDX-License-Identifier: Apache-2.0
# --------------------------------------------------------------------------------------------------
# Semantic project manifest shared by BESA itself and the cpdocs provider.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/internal.cmake")

function(_besa_json_escape INPUT OUTPUT_VARIABLE)
  set(_value "${INPUT}")
  string(REPLACE "\\" "\\\\" _value "${_value}")
  string(REPLACE "\"" "\\\"" _value "${_value}")
  string(REPLACE "\n" "\\n" _value "${_value}")
  string(REPLACE "\r" "\\r" _value "${_value}")
  string(REPLACE "\t" "\\t" _value "${_value}")
  set("${OUTPUT_VARIABLE}" "${_value}" PARENT_SCOPE)
endfunction()

function(_besa_json_string INPUT OUTPUT_VARIABLE)
  _besa_json_escape("${INPUT}" _escaped)
  set("${OUTPUT_VARIABLE}" "\"${_escaped}\"" PARENT_SCOPE)
endfunction()

function(_besa_json_array OUTPUT_VARIABLE)
  set(_items)
  foreach(_value IN LISTS ARGN)
    _besa_json_string("${_value}" _quoted)
    list(APPEND _items "${_quoted}")
  endforeach()
  if(_items)
    string(JOIN ", " _body ${_items})
  else()
    set(_body "")
  endif()
  set("${OUTPUT_VARIABLE}" "[${_body}]" PARENT_SCOPE)
endfunction()

function(_besa_manifest_register_unit)
  cmake_parse_arguments(ARG "GENERATED" "ID;TYPE;ROOT;SOURCE_TYPE" "" ${ARGN})
  _besa_require_no_unparsed("_besa_manifest_register_unit" "${ARG_UNPARSED_ARGUMENTS}")
  foreach(_required ID TYPE ROOT)
    _besa_require_value("_besa_manifest_register_unit" "${_required}" "${ARG_${_required}}")
  endforeach()
  get_property(_count GLOBAL PROPERTY BESA_MANIFEST_UNIT_COUNT)
  if("${_count}" STREQUAL "")
    set(_count 0)
  endif()
  math(EXPR _next "${_count} + 1")
  set_property(GLOBAL PROPERTY BESA_MANIFEST_UNIT_COUNT "${_next}")
  foreach(_field IN ITEMS ID TYPE ROOT SOURCE_TYPE)
    set_property(GLOBAL PROPERTY "BESA_MANIFEST_UNIT_${_count}_${_field}" "${ARG_${_field}}")
  endforeach()
  if(ARG_GENERATED)
    set(_generated TRUE)
  else()
    set(_generated FALSE)
  endif()
  set_property(GLOBAL PROPERTY "BESA_MANIFEST_UNIT_${_count}_GENERATED" "${_generated}")
endfunction()

function(_besa_manifest_type_language TYPE OUTPUT_VARIABLE)
  if(TYPE STREQUAL "c" OR TYPE STREQUAL "cpp" OR TYPE STREQUAL "cuda"
      OR TYPE STREQUAL "hip" OR TYPE STREQUAL "fortran")
    set(_language "${TYPE}")
  else()
    set(_language "")
  endif()
  set("${OUTPUT_VARIABLE}" "${_language}" PARENT_SCOPE)
endfunction()

# The semantic language is what documentation presents to users. The parser language is an
# implementation detail: CUDA and HIP public headers are currently parsed with the C++ frontend.
function(_besa_manifest_parser_language TYPE OUTPUT_VARIABLE)
  if(TYPE STREQUAL "c")
    set(_language c)
  elseif(TYPE STREQUAL "cpp" OR TYPE STREQUAL "cuda" OR TYPE STREQUAL "hip")
    set(_language cpp)
  elseif(TYPE STREQUAL "fortran")
    set(_language fortran)
  else()
    set(_language "")
  endif()
  set("${OUTPUT_VARIABLE}" "${_language}" PARENT_SCOPE)
endfunction()

function(_besa_manifest_standard TYPE OUTPUT_VARIABLE)
  if(TYPE STREQUAL "c" AND DEFINED CMAKE_C_STANDARD AND NOT "${CMAKE_C_STANDARD}" STREQUAL "")
    set(_standard "c${CMAKE_C_STANDARD}")
  elseif((TYPE STREQUAL "cpp" OR TYPE STREQUAL "cuda" OR TYPE STREQUAL "hip")
      AND DEFINED CMAKE_CXX_STANDARD AND NOT "${CMAKE_CXX_STANDARD}" STREQUAL "")
    set(_standard "c++${CMAKE_CXX_STANDARD}")
  else()
    set(_standard "")
  endif()
  set("${OUTPUT_VARIABLE}" "${_standard}" PARENT_SCOPE)
endfunction()

function(_besa_manifest_unit_json INDEX OUTPUT_VARIABLE)
  foreach(_field IN ITEMS ID TYPE ROOT SOURCE_TYPE GENERATED)
    get_property(_${_field} GLOBAL PROPERTY "BESA_MANIFEST_UNIT_${INDEX}_${_field}")
  endforeach()
  _besa_json_string("${_ID}" _id_json)
  _besa_json_string("${_TYPE}" _type_json)
  _besa_manifest_type_language("${_TYPE}" _language)
  if(_language)
    _besa_json_string("${_language}" _language_json)
  else()
    set(_language_json null)
  endif()
  if(_GENERATED)
    set(_generated_json true)
  else()
    set(_generated_json false)
  endif()

  set(_headers)
  set(_sources)
  set(_modules)
  set(_executables)
  if(_TYPE STREQUAL "bin")
    file(GLOB _bin_sources LIST_DIRECTORIES FALSE "${_ROOT}/*.c" "${_ROOT}/*.cc" "${_ROOT}/*.cpp" "${_ROOT}/*.cxx")
    list(APPEND _sources ${_bin_sources})
    list(APPEND _executables ${_bin_sources})
  else()
    if(IS_DIRECTORY "${_ROOT}/include" OR _GENERATED)
      list(APPEND _headers "${_ROOT}/include")
    endif()
    if(IS_DIRECTORY "${_ROOT}/lib" OR _GENERATED)
      list(APPEND _sources "${_ROOT}/lib")
    endif()
    if(_TYPE STREQUAL "fortran" AND (IS_DIRECTORY "${_ROOT}/mod" OR _GENERATED))
      list(APPEND _modules "${_ROOT}/mod")
    endif()
  endif()
  _besa_json_array(_headers_json ${_headers})
  _besa_json_array(_sources_json ${_sources})
  _besa_json_array(_modules_json ${_modules})
  _besa_json_array(_executables_json ${_executables})

  # cpdocs currently consumes public header roots through `api`, while the explicit headers/sources
  # fields make the BESA manifest self-describing and leave room for more language backends.
  set(_api_objects)
  foreach(_header IN LISTS _headers)
    _besa_json_string("${_header}" _path_json)
    if(_GENERATED)
      list(APPEND _api_objects "{\"path\": ${_path_json}, \"generated\": true}")
    else()
      list(APPEND _api_objects "{\"path\": ${_path_json}}")
    endif()
  endforeach()
  if(_api_objects)
    string(JOIN ", " _api_json ${_api_objects})
  else()
    set(_api_json "")
  endif()

  set(_parse_parts)
  _besa_manifest_parser_language("${_TYPE}" _parser_language)
  if(_parser_language)
    _besa_json_string("${_parser_language}" _parser_language_json)
    list(APPEND _parse_parts "\"language\": ${_parser_language_json}")
  endif()
  _besa_manifest_standard("${_TYPE}" _standard)
  if(_standard)
    _besa_json_string("${_standard}" _standard_json)
    list(APPEND _parse_parts "\"standard\": ${_standard_json}")
  endif()
  if(EXISTS "${PROJECT_BINARY_DIR}/compile_commands.json")
    _besa_json_string("${PROJECT_BINARY_DIR}/compile_commands.json" _compile_json)
    list(APPEND _parse_parts "\"compile-database\": ${_compile_json}")
  endif()
  if(_parse_parts)
    string(JOIN ", " _parse_json ${_parse_parts})
  else()
    set(_parse_json "")
  endif()

  if(_SOURCE_TYPE)
    _besa_json_string("${_SOURCE_TYPE}" _source_type_json)
  else()
    set(_source_type_json null)
  endif()
  set(_json
    "{\"id\": ${_id_json}, \"type\": ${_type_json}, \"language\": ${_language_json}, "
    "\"generated\": ${_generated_json}, \"source-type\": ${_source_type_json}, "
    "\"headers\": ${_headers_json}, \"sources\": ${_sources_json}, "
    "\"modules\": ${_modules_json}, \"executables\": ${_executables_json}, "
    "\"api\": [${_api_json}], \"parse\": {${_parse_json}}}"
  )
  string(JOIN "" _json ${_json})
  set("${OUTPUT_VARIABLE}" "${_json}" PARENT_SCOPE)
endfunction()

function(_besa_manifest_units_json OUTPUT_VARIABLE)
  get_property(_count GLOBAL PROPERTY BESA_MANIFEST_UNIT_COUNT)
  if("${_count}" STREQUAL "")
    set(_count 0)
  endif()
  set(_units)
  if(_count GREATER 0)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE 0 ${_last})
      _besa_manifest_unit_json("${_index}" _unit)
      list(APPEND _units "${_unit}")
    endforeach()
  endif()
  if(_units)
    string(JOIN ",\n    " _json ${_units})
  else()
    set(_json "")
  endif()
  set("${OUTPUT_VARIABLE}" "${_json}" PARENT_SCOPE)
endfunction()

function(_besa_manifest_write OUTPUT_FILE)
  get_property(_enabled GLOBAL PROPERTY BESA_ENABLED_FEATURES)
  _besa_json_array(_features_json ${_enabled})
  _besa_json_string("${PROJECT_NAME}" _project_json)
  _besa_manifest_units_json(_units_json)
  get_filename_component(_directory "${OUTPUT_FILE}" DIRECTORY)
  file(MAKE_DIRECTORY "${_directory}")
  file(WRITE "${OUTPUT_FILE}"
    "{\n"
    "  \"besa-manifest\": 1,\n"
    "  \"project\": ${_project_json},\n"
    "  \"features\": ${_features_json},\n"
    "  \"units\": [\n    ${_units_json}\n  ]\n"
    "}\n"
  )
endfunction()

function(_besa_manifest_finalize)
  set(_manifest "${PROJECT_BINARY_DIR}/besa/manifest.json")
  _besa_manifest_write("${_manifest}")
  set(BESA_MANIFEST "${_manifest}" CACHE INTERNAL "BESA semantic project manifest")
endfunction()
