# --------------------------------------------------------------------------------------------------
# SPDX-FileCopyrightText: 2026 BESA developers
# SPDX-License-Identifier: Apache-2.0
# --------------------------------------------------------------------------------------------------
include_guard(GLOBAL)
include(CMakePackageConfigHelpers)

function(_besa_generate_dependency_block OUTPUT_VARIABLE)
  get_property(_dependencies GLOBAL PROPERTY BESA_NORMAL_DEPENDENCIES)
  set(_block "include(CMakeFindDependencyMacro)\n")
  foreach(_record IN LISTS _dependencies)
    string(REPLACE "|" ";" _fields "${_record}")
    list(GET _fields 0 _name)
    list(GET _fields 1 _provider)
    list(GET _fields 2 _version)
    list(GET _fields 3 _components_csv)
    string(REPLACE "," ";" _components "${_components_csv}")

    if(_provider STREQUAL "CMAKE")
      set(_line "find_dependency(${_name}")
      if(_version)
        string(APPEND _line " ${_version}")
      endif()
      if(_components)
        string(REPLACE ";" " " _component_text "${_components}")
        string(APPEND _line " COMPONENTS ${_component_text}")
      endif()
      string(APPEND _line ")\n")
    else()
      _besa_normalize_name("${_name}" _pkg_key)
      set(_line
        "find_dependency(PkgConfig)\npkg_check_modules(BESA_PKG_${_pkg_key} REQUIRED IMPORTED_TARGET ${_name})\n"
      )
    endif()
    string(APPEND _block "${_line}")
  endforeach()
  set("${OUTPUT_VARIABLE}" "${_block}" PARENT_SCOPE)
endfunction()

function(_besa_package_finalize)
  get_property(_targets GLOBAL PROPERTY BESA_INSTALL_TARGETS)
  if(NOT _targets)
    return()
  endif()
  list(REMOVE_DUPLICATES _targets)

  include(GNUInstallDirs)
  foreach(_target IN LISTS _targets)
    get_target_property(_type "${_target}" TYPE)
    if(_type STREQUAL "EXECUTABLE")
      install(TARGETS "${_target}" EXPORT "${PROJECT_NAME}Targets" RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
    else()
      get_target_property(_header_sets "${_target}" HEADER_SETS)
      if(_header_sets)
        install(
          TARGETS "${_target}"
          EXPORT "${PROJECT_NAME}Targets"
          FILE_SET HEADERS DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
          ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
          LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
          RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
        )
      else()
        install(
          TARGETS "${_target}"
          EXPORT "${PROJECT_NAME}Targets"
          ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
          LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
          RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
        )
      endif()
    endif()
  endforeach()

  set(_package_dir "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}")
  install(
    EXPORT "${PROJECT_NAME}Targets"
    FILE "${PROJECT_NAME}Targets.cmake"
    NAMESPACE "${PROJECT_NAME}::"
    DESTINATION "${_package_dir}"
  )

  _besa_generate_dependency_block(_dependencies)
  set(_generated_dir "${PROJECT_BINARY_DIR}/besa/package")
  file(MAKE_DIRECTORY "${_generated_dir}")
  set(_config "${_generated_dir}/${PROJECT_NAME}Config.cmake")
  file(WRITE "${_config}"
    "# Generated by BESA.\n"
    "${_dependencies}"
    "include(\"\${CMAKE_CURRENT_LIST_DIR}/${PROJECT_NAME}Targets.cmake\")\n"
    "set(${PROJECT_NAME}_VERSION_STRING \"${PROJECT_SEMVER}\")\n"
  )

  write_basic_package_version_file(
    "${_generated_dir}/${PROJECT_NAME}ConfigVersion.cmake"
    VERSION "${PROJECT_VERSION}"
    COMPATIBILITY SameMajorVersion
  )
  install(
    FILES
      "${_config}"
      "${_generated_dir}/${PROJECT_NAME}ConfigVersion.cmake"
    DESTINATION "${_package_dir}"
  )
endfunction()
