# --------------------------------------------------------------------------------------------------
# SPDX-FileCopyrightText: 2026 BESA developers
# SPDX-License-Identifier: Apache-2.0
# --------------------------------------------------------------------------------------------------
# Semantic project units and extensible directory types.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/internal.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/keyso.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/manifest.cmake")

function(_besa_subdir_type_property TYPE FIELD OUTPUT_VARIABLE)
  _besa_normalize_name("${TYPE}" _type)
  set("${OUTPUT_VARIABLE}" "BESA_SUBDIR_TYPE_${_type}_${FIELD}" PARENT_SCOPE)
endfunction()

function(_besa_subdir_register_builtin TYPE LANGUAGE)
  _besa_subdir_type_property("${TYPE}" KIND _kind_property)
  set_property(GLOBAL PROPERTY "${_kind_property}" builtin)
  _besa_subdir_type_property("${TYPE}" LANGUAGE _language_property)
  set_property(GLOBAL PROPERTY "${_language_property}" "${LANGUAGE}")
  set_property(GLOBAL APPEND PROPERTY BESA_SUBDIR_TYPES "${TYPE}")
endfunction()

function(_besa_subdir_type_get TYPE FIELD OUTPUT_VARIABLE)
  _besa_subdir_type_property("${TYPE}" "${FIELD}" _property)
  get_property(_set GLOBAL PROPERTY "${_property}" SET)
  if(NOT _set)
    set("${OUTPUT_VARIABLE}" "" PARENT_SCOPE)
    return()
  endif()
  get_property(_value GLOBAL PROPERTY "${_property}")
  set("${OUTPUT_VARIABLE}" "${_value}" PARENT_SCOPE)
endfunction()

function(_besa_subdir_initialize_types)
  get_property(_done GLOBAL PROPERTY BESA_SUBDIR_TYPES_INITIALIZED)
  if(_done)
    return()
  endif()
  _besa_subdir_register_builtin(c C)
  _besa_subdir_register_builtin(cpp CXX)
  _besa_subdir_register_builtin(cuda CUDA)
  _besa_subdir_register_builtin(hip HIP)
  _besa_subdir_register_builtin(fortran Fortran)
  _besa_subdir_register_builtin(bin "")
  set_property(GLOBAL PROPERTY BESA_SUBDIR_TYPES_INITIALIZED TRUE)
endfunction()

# Register an extension type. GENERATED types receive a BESA-owned output prefix and must resolve to
# one of the concrete built-in types. The callback may define its own additional arguments; BESA
# always passes SOURCE_DIR, BUILD_DIR, OUTPUT_DIR, and OUTPUT_TARGET_VARIABLE.
function(besa_register_subdirectory_type TYPE)
  _besa_require_config_open("besa_register_subdirectory_type")
  if("${TYPE}" STREQUAL "")
    _besa_fatal("besa_register_subdirectory_type" "type name is required")
  endif()
  cmake_parse_arguments(ARG "GENERATED" "FUNCTION;RESOLVES_TO" "" ${ARGN})
  _besa_require_no_unparsed("besa_register_subdirectory_type" "${ARG_UNPARSED_ARGUMENTS}")
  foreach(_required FUNCTION RESOLVES_TO)
    _besa_require_value("besa_register_subdirectory_type" "${_required}" "${ARG_${_required}}")
  endforeach()
  _besa_subdir_initialize_types()
  _besa_subdir_type_get("${TYPE}" KIND _existing)
  if(_existing)
    _besa_fatal("besa_register_subdirectory_type" "TYPE '${TYPE}' is already registered")
  endif()
  _besa_subdir_type_get("${ARG_RESOLVES_TO}" KIND _resolved_kind)
  if(NOT _resolved_kind STREQUAL "builtin")
    _besa_fatal("besa_register_subdirectory_type" "RESOLVES_TO must name a built-in type")
  endif()
  if(NOT COMMAND "${ARG_FUNCTION}")
    _besa_fatal("besa_register_subdirectory_type" "FUNCTION '${ARG_FUNCTION}' does not exist")
  endif()
  if(NOT ARG_GENERATED)
    _besa_fatal("besa_register_subdirectory_type" "custom subdirectory types must currently be GENERATED")
  endif()

  foreach(_field_value IN ITEMS "KIND;custom" "FUNCTION;${ARG_FUNCTION}" "RESOLVES_TO;${ARG_RESOLVES_TO}" "GENERATED;TRUE")
    string(REPLACE ";" "|" _record "${_field_value}")
    string(REPLACE "|" ";" _parts "${_record}")
    list(GET _parts 0 _field)
    list(GET _parts 1 _value)
    _besa_subdir_type_property("${TYPE}" "${_field}" _property)
    set_property(GLOBAL PROPERTY "${_property}" "${_value}")
  endforeach()
  set_property(GLOBAL APPEND PROPERTY BESA_SUBDIR_TYPES "${TYPE}")
endfunction()



macro(_besa_subdir_enable_language TYPE)
  if(NOT "${TYPE}" STREQUAL "bin")
    _besa_subdir_type_get("${TYPE}" LANGUAGE _besa_language)
    if(_besa_language)
      get_property(_besa_enabled_languages GLOBAL PROPERTY ENABLED_LANGUAGES)
      if(NOT "${_besa_language}" IN_LIST _besa_enabled_languages)
        enable_language("${_besa_language}")
      endif()
    endif()
  endif()
endmacro()

macro(_besa_subdir_enable_bin_languages ROOT)
  file(GLOB _besa_bin_sources LIST_DIRECTORIES FALSE "${ROOT}/*.c" "${ROOT}/*.cc" "${ROOT}/*.cpp" "${ROOT}/*.cxx")
  set(_besa_need_c FALSE)
  set(_besa_need_cxx FALSE)
  foreach(_besa_source IN LISTS _besa_bin_sources)
    get_filename_component(_besa_extension "${_besa_source}" EXT)
    if(_besa_extension STREQUAL ".c")
      set(_besa_need_c TRUE)
    else()
      set(_besa_need_cxx TRUE)
    endif()
  endforeach()
  get_property(_besa_enabled_languages GLOBAL PROPERTY ENABLED_LANGUAGES)
  if(_besa_need_c AND NOT "C" IN_LIST _besa_enabled_languages)
    enable_language(C)
  endif()
  get_property(_besa_enabled_languages GLOBAL PROPERTY ENABLED_LANGUAGES)
  if(_besa_need_cxx AND NOT "CXX" IN_LIST _besa_enabled_languages)
    enable_language(CXX)
  endif()
endmacro()

function(_besa_subdir_filter_metadata LIST_VARIABLE)
  set(_values ${${LIST_VARIABLE}})
  list(FILTER _values EXCLUDE REGEX "/\\.[^/]+$")
  set("${LIST_VARIABLE}" "${_values}" PARENT_SCOPE)
endfunction()

function(_besa_subdir_lower_library ROOT TYPE GENERATED)
  set(_library "lib${PROJECT_NAME}")
  file(GLOB_RECURSE _headers LIST_DIRECTORIES FALSE CONFIGURE_DEPENDS "${ROOT}/include/*")
  file(GLOB_RECURSE _sources LIST_DIRECTORIES FALSE CONFIGURE_DEPENDS "${ROOT}/lib/*")
  if(TYPE STREQUAL "fortran")
    file(GLOB_RECURSE _modules LIST_DIRECTORIES FALSE CONFIGURE_DEPENDS "${ROOT}/mod/*")
  else()
    set(_modules)
  endif()
  _besa_subdir_filter_metadata(_headers)
  _besa_subdir_filter_metadata(_sources)
  _besa_subdir_filter_metadata(_modules)

  if(_headers OR _sources OR _modules)
    if(NOT TARGET "${_library}")
      besa_add_library(NAME "${_library}")
    endif()
    if(_sources OR _modules)
      target_sources("${_library}" PRIVATE ${_sources} ${_modules})
    endif()
    if(_headers)
      target_sources("${_library}" PUBLIC FILE_SET HEADERS BASE_DIRS "${ROOT}/include" FILES ${_headers})
    endif()
    if(IS_DIRECTORY "${ROOT}/include" OR GENERATED)
      target_include_directories(
        "${_library}" PUBLIC
        $<BUILD_INTERFACE:${ROOT}/include>
        $<INSTALL_INTERFACE:include>
      )
    endif()
    if(GENERATED AND TARGET codegen)
      add_dependencies("${_library}" codegen)
    endif()
  endif()
endfunction()

function(_besa_subdir_lower_bin ROOT)
  file(GLOB _sources LIST_DIRECTORIES FALSE CONFIGURE_DEPENDS "${ROOT}/*.c" "${ROOT}/*.cc" "${ROOT}/*.cpp" "${ROOT}/*.cxx")
  _besa_subdir_filter_metadata(_sources)
  foreach(_source IN LISTS _sources)
    get_filename_component(_target "${_source}" NAME_WE)
    set(_links)
    if(TARGET "lib${PROJECT_NAME}")
      list(APPEND _links "${PROJECT_NAME}::lib${PROJECT_NAME}")
    endif()
    besa_add_executable(NAME "${_target}" SOURCES "${_source}" LINK_LIBRARIES ${_links})
  endforeach()
endfunction()

function(_besa_subdir_lower ROOT TYPE GENERATED)
  if(TYPE STREQUAL "bin")
    _besa_subdir_lower_bin("${ROOT}")
  else()
    _besa_subdir_lower_library("${ROOT}" "${TYPE}" "${GENERATED}")
  endif()
endfunction()

# Add one semantic project unit. CONDITION names a Keyso feature space; the unit is selected when
# the concrete enabled feature set matches at least one pattern in that space.
macro(besa_add_subdirectory)
  _besa_require_config_complete("besa_add_subdirectory")
  cmake_parse_arguments(BESA_SUBDIR "" "DIRECTORY;TYPE;CONDITION" "ARGS" ${ARGN})
  _besa_require_no_unparsed("besa_add_subdirectory" "${BESA_SUBDIR_UNPARSED_ARGUMENTS}")
  _besa_require_value("besa_add_subdirectory" "DIRECTORY" "${BESA_SUBDIR_DIRECTORY}")
  _besa_require_value("besa_add_subdirectory" "TYPE" "${BESA_SUBDIR_TYPE}")
  _besa_subdir_initialize_types()
  _besa_subdir_type_get("${BESA_SUBDIR_TYPE}" KIND _besa_kind)
  if(NOT _besa_kind)
    _besa_fatal("besa_add_subdirectory" "unknown TYPE '${BESA_SUBDIR_TYPE}'")
  endif()

  set(_besa_selected TRUE)
  if(BESA_SUBDIR_CONDITION)
    get_property(_besa_features GLOBAL PROPERTY BESA_ENABLED_FEATURES)
    _besa_keyso_matches("${BESA_SUBDIR_CONDITION}" "${_besa_features}" _besa_selected)
  endif()

  if(_besa_selected)
    get_filename_component(_besa_source "${BESA_SUBDIR_DIRECTORY}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT IS_DIRECTORY "${_besa_source}")
      _besa_fatal("besa_add_subdirectory" "DIRECTORY does not exist: ${_besa_source}")
    endif()
    file(RELATIVE_PATH _besa_relative "${PROJECT_SOURCE_DIR}" "${_besa_source}")
    string(REGEX REPLACE "[^A-Za-z0-9_.-]" "_" _besa_unit_key "${_besa_relative}")
    set(_besa_build "${PROJECT_BINARY_DIR}/besa/subdirectories/${_besa_unit_key}")
    file(MAKE_DIRECTORY "${_besa_build}")
    if(_besa_kind STREQUAL "builtin")
      _besa_manifest_register_unit(ID "${_besa_relative}" TYPE "${BESA_SUBDIR_TYPE}" ROOT "${_besa_source}")
      if(BESA_SUBDIR_TYPE STREQUAL "bin")
        _besa_subdir_enable_bin_languages("${_besa_source}")
      else()
        _besa_subdir_enable_language("${BESA_SUBDIR_TYPE}")
      endif()
      _besa_subdir_lower("${_besa_source}" "${BESA_SUBDIR_TYPE}" FALSE)

    else()
      _besa_subdir_type_get("${BESA_SUBDIR_TYPE}" FUNCTION _besa_function)
      _besa_subdir_type_get("${BESA_SUBDIR_TYPE}" RESOLVES_TO _besa_resolved)
      _besa_subdir_type_get("${BESA_SUBDIR_TYPE}" GENERATED _besa_generated)
      if(NOT _besa_generated)
        _besa_fatal("besa_add_subdirectory" "custom TYPE '${BESA_SUBDIR_TYPE}' is not generated")
      endif()
      if(NOT DEFINED BESA_CODEGEN_DIRECTORY OR "${BESA_CODEGEN_DIRECTORY}" STREQUAL "")
        besa_workspace_initialize()
      endif()
      set(_besa_output "${BESA_CODEGEN_DIRECTORY}/${_besa_unit_key}")
      foreach(_besa_directory IN ITEMS include lib)
        file(MAKE_DIRECTORY "${_besa_output}/${_besa_directory}")
      endforeach()
      if(_besa_resolved STREQUAL "fortran")
        file(MAKE_DIRECTORY "${_besa_output}/mod")
      endif()

      set(_besa_target "")
      cmake_language(
        CALL "${_besa_function}"
        SOURCE_DIR "${_besa_source}"
        BUILD_DIR "${_besa_build}"
        OUTPUT_DIR "${_besa_output}"
        OUTPUT_TARGET_VARIABLE _besa_target
        ${BESA_SUBDIR_ARGS}
      )
      if(_besa_target)
        _besa_codegen_register_target("${_besa_unit_key}" "${_besa_target}")
      endif()
      _besa_manifest_register_unit(
        ID "${_besa_relative}" TYPE "${_besa_resolved}" ROOT "${_besa_output}"
        SOURCE_TYPE "${BESA_SUBDIR_TYPE}" GENERATED
      )
      if(_besa_resolved STREQUAL "bin")
        _besa_subdir_enable_bin_languages("${_besa_output}")
      else()
        _besa_subdir_enable_language("${_besa_resolved}")
      endif()
      _besa_subdir_lower("${_besa_output}" "${_besa_resolved}" TRUE)
      if(_besa_target AND TARGET "lib${PROJECT_NAME}")
        add_dependencies("lib${PROJECT_NAME}" "${_besa_target}")
      endif()
    endif()
  endif()
  unset(BESA_SUBDIR_DIRECTORY)
  unset(BESA_SUBDIR_TYPE)
  unset(BESA_SUBDIR_CONDITION)
  unset(BESA_SUBDIR_ARGS)
endmacro()

_besa_subdir_initialize_types()
